### ISSUE TITLE
deskflow: new

### ISSUE THREAD

**Issue by nbolton** [teknowledgist/Chocolatey-packages#108]
Package id: deskflow
New version: 1.17.0.0

---

### New plan

Introduce `deskflow` as a new package at `v1.17.0.0` and update the description of `synergy` to point people to `deskflow` as the new official upstream of Synergy.

### Original message 

Hi @teknowledgist (and @ferventcoder) :wave: 

I am a developer of [Synergy](https://github.com/symless/synergy) (the free community edition).

It looks like the choco package for [Synergy](https://community.chocolatey.org/packages/synergy) is very old and needs updating to v1.15. I think it would also benefit from a title (perhaps "Synergy 1 Community Edition") and logo change too.

Please could we get this package updated to Synergy 1 Community Edition? Let me know if you need anything for this. I believe it should be the free community edition to match [`brew install synergy`](https://formulae.brew.sh/formula/synergy-core).

**Comment by teknowledgist** [comment]
Hi, @nbolton.  

You might note at the bottom of the [Synergy package description](https://community.chocolatey.org/packages/synergy) the note about it being the "last build".  The reason for that is Chocolatey relies on downloading/embedding application (installer) binaries.  I can't(1) compile an application for Windows on the fly, and if I compiled it prior to updating the package, it would not be an official binary.  Users would have no real way to verify that I didn't "mess" with it before compiling.  

Basically, (as you are certainly very aware) Windows and Linux/MacOS are very different beasts. (At least from my semi-skilled viewpoint, but I am willing to admin that maybe they are more similar at a fundamental level than I understand.)

I'm open to options if you have any suggestions.


(1) Even if I had the knowledge/skill to auto-compile during a Chocolatey install, doing it on the user-side would require making the package dependent on at least one compiler which complicates users' setups and isn't really required to use the application.

**Comment by teknowledgist** [comment]
Basically, yes.  

If the binary isn't too big (and assuming the license still allows it), I can embed it into the Chocolatey package, but either way, there needs to be a way for users (and Chocolatey Community repository moderators) to verify that the binary file(s) downloaded by Chocolatey or embedded in the package have not changed from the official build.  

If you don't want to make the binaries publicly downloadable, but are willing to allow the Chocolatey package to distribute them (embedded), we might be able to convince the moderators of the authenticity if you post the SHA256 hashes of the binaries while only providing them to the package (i.e. me).  A `VERIFICATION.txt` file is standard for embedded Chocolatey packages.  I'm not sure that really makes sense, but you have been offering only the source code and no binaries for a few years now, so 🤷 .

**Comment by teknowledgist** [comment]
I can easily either rename the synergy Chocolatey package to be "Synergy 1 Community Edition" or create a new "synergy-community" (or similar) Chocolatey package to separate the old from the new.

The more I think about it though, the weirder the proposal to "split" the binary distribution seems to me.  In order to be approved by moderators, the hash would need to be publicly available, but what advantage would that be for anyone?  You'd be saying, "Here is the official hash for a binary I'm not going to give you, but is available embedded in this thing over there that requires you understand a totally different piece of software which you might not use for anything else."

If you want to create a free, community edition, I think you should allow folks to get the binary from you.  Certainly, you can promote an "easy" way to install it via Chocolatey, and I'm happy to maintain the package, but if you want it to be used, make it easy with multiple paths to success.  IMHO, of course.  

It's your baby though, so all I can do is try to help you accomplish your vision.  😄

**Comment by nbolton** [comment]
> rename the synergy Chocolatey package to be "Synergy 1 Community Edition"

I think this would be the way to go; keep the ID as `synergy` and have the app title as "Synergy 1 Community Edition".

> the weirder the proposal to "split" the binary distribution seems to me

I think I'm inclined to agree.

> I think you should allow folks to get the binary from you. Certainly, you can promote an "easy" way to install it via Chocolatey, and I'm happy to maintain the package, but if you want it to be used, make it easy with multiple paths to success. IMHO, of course.

It's a good opinion and an approach I am strongly considering.

Would it need to be signed? I ask because it'd need to be separate from the code signing we use for the licensed packages, so if it was signed under my name (personally, not through the business) with an open source signing certificate (e.g. [from Certum](https://shop.certum.eu/open-source-code-signing-code.html#:~:text=What%20is%20Open%20Source%20Code%20Signing%20Certificate%3F)) then maybe that could work.

> It's your baby though, so all I can do is try to help you accomplish your vision. 😄

Thank you! I appreciate the support.

**Comment by teknowledgist** [comment]
> Would it need to be signed?

Honestly, I don't know.  I haven't gotten any pushback from any of the many dozens of packages I maintain, but I also haven't confirmed that the applications are all signed.  My guess is that Chocolatey and the automatic package verification doesn't care, and that Windows Defender is going to be the one to complain/block the execution of the binary (whether the installer or the actual application).

**Comment by nbolton** [comment]
> Windows Defender

Ok good to know. I'll build a CE package and throw it at Windows Defender to see how it behaves. It used to be the case that you didn't need to sign (it'd show you a bunch of warnings) but I don't know if Microsoft have gotten more strict in Windows 11. 

I'll update here with my findings.

**Comment by nbolton** [comment]
Quick update: Windows 10 doesn't seem to care if it's unsigned. I'll test on Windows 11. Haven't heard back from Certum about the open source code signing cert, but perhaps it's not that important?

**Comment by nbolton** [comment]
FYI, I'm still working on this. Blocker is the upstream project rename: https://github.com/deskflow/deskflow/discussions/7517

**Comment by nbolton** [comment]
> > rename the synergy Chocolatey package to be "Synergy 1 Community Edition"
> 
> I think this would be the way to go; keep the ID as `synergy` and have the app title as "Synergy 1 Community Edition".

@teknowledgist Sorry, going to a 180 on this. I think we should rename `synergy` to `deskflow` in Chocolatey repo.

I'll update the PR to point at [Deskflow v1.17.0](https://github.com/deskflow/deskflow/releases/tag/v1.17.0)

**Comment by nbolton** [comment]
> I would suggest that I/we make a new package for Deskflow.

Sure, whatever you think is best.

I wonder if we should either update the `synergy` package info to recommend using `deskflow`, or perhaps remove `synergy` entirely since the package is so old now.

> We might want to just fail the package if Synergy is installed with a message for the user to remove it.

Yeah, I think perhaps this simpler approach would be safest.

**Comment by teknowledgist** [comment]
I'm not sure how to deal with the "continuous" build.  It's the first time I've seen that.

Normally, I (and other maintainers) grab the version number and installer from the "latest" release (https://github.com/deskflow/deskflow/releases/latest).  I could do that, but the Chocolatey public repository is not built to handle a continuous update schedule, so the version would be whatever is available from the "latest" URL at the moment the package updater runs.  

Some package updaters are scheduled to run as often as every hour, but I don't have that automated.  Besides, there is no guarantee that the version I would grab would be stable, nor that it would quickly be replaced with a "fixed" version.  Also, essential to package security is the ability to compare checksums between the official download and the download used for the package version.  If the "continuous" is changing all the time without a version-fixed download, that checksum comparison is impossible.

I'm sure I can modify the update check to look at the second-most-recent release, but it's going to take some fiddling.  (Otherwise, I'd be done today.)

**Comment by nbolton** [comment]
> I'm not sure how to deal with the "continuous" build. It's the first time I've seen that.

Packagers can ignore continuous build. The reason why we put it as latest is to encourage people to use and test it so we can find bugs sooner.

Packagers should use the latest stable, which is linked to from the "stable" button on the readme (currently v1.17.0).

@sithlord48 FYI, more package maintainers getting caught off guard by continuous being latest. Should we put something on our readme?

**Comment by sithlord48** [comment]
Any upstream that wants can track upstream but they are gonna get alot of updates..

**Comment by nbolton** [comment]
> Any upstream that wants can track upstream but they are gonna get alot of updates..

@sithlord48 I believe it's a different problem; packagers _don't_ want to track continuous builds. They want a way to track _latest_ stable. Most projects use the "latest" URL (in our case, `https://github.com/deskflow/deskflow/releases/latest`) to track the latest stable, but our project is a bit unusual in that we use that for latest continuous build of master.

@teknowledgist Am I interpreting your point of view correctly?

**Comment by nbolton** [comment]
> The newest stable is always our continuous release.

Let's move this to a discussion on Deskflow: https://github.com/deskflow/deskflow/discussions/7837

**Comment by teknowledgist** [comment]
> > Any downstream that wants can track continuous but they are gonna get alot of updates.
> 
> @sithlord48 I believe it's a different problem; packagers _don't_ want to track continuous builds. They want a way to track _latest_ stable. Most projects use the "latest" URL (in our case, `https://github.com/deskflow/deskflow/releases/latest`) to provide the latest stable, but our project is a bit unusual in that we use that for latest continuous build of master.
> 
> @teknowledgist Am I interpreting your point of view correctly?

Yes, for my part at least.  I don't want to speak for other package maintainers, but using the "latest" URL is the default method most Chocolatey packages use to determine new releases.  In fact, the code to query the GitHub API requires a specific release tag if it is not "latest" which then becomes a catch-22:  To know the version, you have to know the tag which is (usually) the version.

Example of the problem with using the continuous build:  I create a package based on the continuous build (currently, 1.17.0.166).  

* If I embed the installer in the Chocolatey package, and Joe User comes along to use it next week.  He can't verify that I didn't "mess" with what is embedded in the package because if he downloads the continuous build, it will be a different version and the checksum won't match.  Joe User can no longer trust the package doesn't have a Trojan horse installer.
* If I don't embed the installer, the Chocolatey package has to download the installer, and to ensure that it is getting the same file the package was constructed with, it compares the checksums.  They will also not match and the package install will fail.  

The GitHub API is robust enough that I'm sure there is a way to determine the next-to-latest release, but that will take some additional work/time.

**Comment by sithlord48** [comment]
and that is why for most package distributions they will not want to use the continuous tag. but instead the tag of the version they are releasing.

**Comment by nbolton** [comment]
> using the "latest" URL is the default method most Chocolatey packages use to determine new releases

For the time being, @sithlord48 is set on keeping continuous as latest, so unfortunately I think that option is unavailable to us for the time being.

> The GitHub API is robust enough that I'm sure there is a way to determine the next-to-latest release, but that will take some additional work/time.

Ah, well, we already did this logic as it happens:
https://api.deskflow.org/version

This queries the releases via the GitHub API and finds the latest one that is not `continuous`. It's hosted on Cloudflare and is used by the GUI to check if there's an update available, so it is highly reliable.

**Comment by teknowledgist** [comment]
It looks like the versioning and naming are going to be stable going forward the API gets me the version anyway, so I went ahead and submitted [the deskflow Chocolatey package](https://community.chocolatey.org/packages/deskflow) to the community repository.  

If I have to make tweak related to URL when the next version comes out, I will do that.  If there is anything you would like changed about the package, let me know.  Because the installer is embedded, it will probably take a week (to many weeks) for this to be approved by the moderators, so now is the time to fix any descriptive wording or other metadata.  Just let me know.

Peace.

**Comment by sithlord48** [comment]
There will be a sums.txt you can use to get sha256sums as well as the build version if you want to deploy the continuous or can otherwise use the checksums

**Comment by sithlord48** [comment]
we have released 1.17.1 with slightly different links

**Comment by teknowledgist** [comment]
Yep.  I have the 1.17.1 Chocolatey package all set, but I can't submit it to the community repository until the 1.17.0 version is cleared by the moderators.  That takes a few weeks for initial packages, and usually progresses quickly with subsequent versions until it is just a couple hours with the automated testing queue being the ultimate bottleneck.
