### ISSUE TITLE
DraftSight 2019 for Windows® is offered in paid versions only.

### ISSUE THREAD

**Issue by basictheprogram** [teknowledgist/Chocolatey-packages#15]
Opening an issue to discuss what to do next with DraftSight 2019 and beyond.

DraftSight 2019 for Windows® is offered in paid versions only.

Once you download and install DraftSight 2019 (free 30-day trial or purchased version), you will no longer be able to redownload or access any previous free version of DraftSight (2018 or earlier).

All free versions of DraftSight (2018 or earlier) will cease to run after 12/31/2019.

https://www.3ds.com/products-services/draftsight-cad-software/download-draftsight/

**Comment by basictheprogram** [comment]
2019 has a new dialog on installation?

<img width="497" alt="1__tanner_host-114_castle_real-time_com___Users_tanner_projects_crossfire_archdb_src__python3_7__and_chocolatey_test_environment_windows_2016__Running_" src="https://user-images.githubusercontent.com/6723257/56839408-faba7080-6847-11e9-9c0c-7578be4214e2.png">

Accept license?

<img width="492" alt="chocolatey_test_environment_windows_2016__Running_" src="https://user-images.githubusercontent.com/6723257/56839542-99df6800-6848-11e9-81dd-75babaabe090.png">

<img width="494" alt="chocolatey_test_environment_windows_2016__Running_" src="https://user-images.githubusercontent.com/6723257/56839639-196d3700-6849-11e9-87fd-8a0b86e85a26.png">

@teknowledgist do you want me to autokey (autoit) or look to see if we can default the 30-day trial via silent installer or look to create .mst to keep things silent?

The current silent installer options give an error dialog when trying to run Draftsight. Which I assume is because the 30 day trial option was not selected on install.

**Comment by basictheprogram** [comment]
Using the current installation options of Draftsight I receive this error dialog

<img width="500" alt="1__tanner_host-114_castle_real-time_com___Users_tanner_projects_crossfire_archdb_src__python3_7__and_chocolatey_test_environment_windows_2016__Running_" src="https://user-images.githubusercontent.com/6723257/56840182-bd57e200-684b-11e9-907b-289890ac11f6.png">

**Comment by teknowledgist** [comment]
@basictheprogram  Sorry for the delay.  I am just getting back from vacation.  I will take a look at this, but note that I have already designated Draftsight as "discontinued".  I am not a fan of promoting free trials with no free use option, so I'm not inclined to put a bunch of time into getting this to work (and keeping it working as autohotkey often requires adjustments moving forward).

**Comment by basictheprogram** [comment]
We use this extensively so I'll keep working the package but  just pull the installer for a local CIFS share and see if I can get a .MST file to work for licensing and answering the dialogs. 

As long as I do not commit the installer or anything it should be old for me to push the chocolatey package changes to github? People would have to change things to point to their own CIFS share for the installer but everything else should work.

Does chocolatey allow that?

**Comment by teknowledgist** [comment]
@basictheprogram Chocolatey can definitely do that.

Somewhere in the Chocolatey documentation (I'm too lazy to find it right now.), they mention that "most" business-use of Chocolatey is for private/internal packages.  In my previous job, I had several internal packages for commercial software that "lived" on a CIFS share.  See my [local packages](https://github.com/teknowledgist/Chocolatey-packages/tree/master/Local) for examples.  I will probably be creating some local packages for my new job too if I can ever wrap my head around the mess.

If you verify that you can use an MST for a silent install, I'll copy this package and modify it as an internal package for you (if you want).

**Comment by basictheprogram** [comment]
I see you moved draftsight to `discontinued/draftsight/draftsight.nuspec` would you like my PR to that location? 

OR

Maybe pull the package out into it's own repository?

OR

Should I just maintain my own repository and not present you PR's?

I have a working package putting the .msi INTO the package (think this is called a shim?) and that fits my needs right now but I'm happy to share the changes so other can do something similar by downloading their own copy of the DraftSight 2019 installer.

Let me know.

Thanks.

**Comment by basictheprogram** [comment]
Doesn't seem to be a lot of activity on the draftsight package? When I move directory to  a New Repository I only get few commits?
```
git clone git@github.com:teknowledgist/Chocolatey-packages.git
git filter-branch --prune-empty --subdirectory-filter discontinued/draftsight master
```
```
git log
commit 6267635486cf3d84560217470b765c0db50372d1 (HEAD -> master)
Author: teknowledgist <teknowledgist@users.noreply.github.com>
Date:   Sat Mar 23 12:39:26 2019 -0400

    lastools,qcad,marcedit,draftsight
```

**Comment by basictheprogram** [comment]
@teknowledgist let me know if you are ok with the changes I made and if you still want your name associated with the package.

**Comment by teknowledgist** [comment]
@basictheprogram the `automatic/draftsight` folder is unnecessary and there only because I didn't change a reference path.

There has not been any activity on the package because there hasn't been any need.  Certainly, I would update it if I could make the 2018.03 version work, but the download is gone (as far as I can tell).

I am not sure what changes you have made.  I don't see any PRs or differences between my repository and yours.  As I said previously, if you know how to install the 2019 version silently, I am willing to update and submit the package.  As a co-maintainer, you can certainly do the same, but I'm probably more familiar with the process.  If you want to take the helm, feel free to drop me as a maintainer.  It really doesn't matter to me either way.

One thing you should know... I had another package that I tried to submit with a transform (.MST) file, and the moderators didn't like that.  The installer is verifiable against the publisher and the PoSh scripts and .nuspec are just plain text that can be inspected.  An MST is a custom binary file that they have no way to verify that it is safe.  Almost certainly, an accepted *public* package will need to work without an MST file.  That of course makes this whole thing more challenging.

If you are making/using a private/internal package for your own needs, you can do anything you want, of course.  It would be best in that case if you take my name out, but unless you have a Chocolatey package server, nobody would be seeing the authors anyway.  

My offer to help with the code for a package using what you figure out for a silent install still stands even if you want to keep it internal.  I can design the package accept paths for a local installer and local MST so you could use the same format for future versions of DraftSight.

**Comment by basictheprogram** [comment]
I created a new repo at https://github.com/basictheprogram/chocolatey-draftsight/tree/v2019 as I didn't know about how to do private packages or if you wanted to still be involved in the package maintenance.  I could just copy my changes over the stop of your package? Let me know what you want me to do. Thanks.

**Comment by teknowledgist** [comment]
@basictheprogram I pushed an updated package and have moved the package to the "manual" section of my repository.  I will update the package (assuming I can) when I notice it is outdated.  Feel free to let me know if it gets out of date or breaks.
