### ISSUE TITLE
Artifex dropped support for gsview

### ISSUE THREAD

**Issue by markuspeloquin** [teknowledgist/Chocolatey-packages#23]
It looks like Artifex [dropped gsview](https://gsview.com/) from their website. The URL in https://github.com/teknowledgist/Chocolatey-packages/blob/master/manual/gsview/tools/chocolateyInstall.ps1 gives a 404. I found it [elsewhere on the internet](https://www.simfit.org.uk/download.html) with a matching SHA2-256 sum. I'm not sure if there are any official hosts, of the exe or the source (or if the source exists, even).

**Comment by teknowledgist** [comment]
Hi, @markuspeloquin .  Thanks for asking about this.  I knew they had stopped supporting it, but I didn't know yet that they had cut off downloads.

The problem is the license.  The Artifex license does not allow distribution, so while the download from other locations may be bitwise-equivilent and work just fine, it's not a legal distribution.  Thus, I can't use it.  

I am trying to contact Artifex to see if they will give me/Chocolatey.org a distribution exception so it doesn't become completely abandoned.  So far, no responses.  

It's frustrating when companies abandon software like this, but short of a possible lawsuit against them (which would probably not work), there isn't much else we can do.  

If you need to install gsview on a bunch of machines ongoing in the future and want to use a chocolatey package, I could give you the modified files to build an embedded gsview package that you could use within your organization.  The only thing I can't give you is the installer (for legal reasons), but you know where to grab it.  😄  I can tell you how to complete the package.

**Comment by teknowledgist** [comment]
Hello,
Thank you for contacting us.  Please see my comments below.
___________________________________

1305 Grant Avenue, suite 200
Novato, CA  94945

Miles Jones, President

tel:  +1 415 492 9861
fax:  +1 415 492 9862
e-mail:  miles.jones@artifex.com
www.artifex.com

>
> You have discontinued GSView and no longer allow folks to download it, but
> there are still users who could benefit from it even if you don't support
> it. Please consider granting permission to distribute the final installer
> on the Chocolatey public repository. I am the maintainer of the package (
> https://chocolatey.org/packages/GSView) that is broken. Professionally, I
> work in an academic research environment where older software like gsview
> is still used.
>

Unfortunately GSView has been abandoned for several years and is many
versions behind the current AGPL Ghostscript. In addition, GSView has
several serious security flaws.  It would take too much work for us to
rebuild it to an acceptable level.

> However, now we have to find it on other sites where it is being
> distributed against your license.

We have a solemn obligation to protect our copyrights.  If you let us know
what sites offer GSView without proper adherence to license terms, please
let us know and we will pursue it.

> If my Chocolatey package could (legally) embed the installer and note that
> it is EOL, it could still be safely found and used with no harm or cost to
> you. Thanks!

I appreciate your offer, but this is not something we are going to spend
engineering resources on at this time.

Best regards,
Miles Jones

**Comment by teknowledgist** [comment]
Given their statement above, I have requested the admins of the Chocolatey.org repository "de-list" the gsview package as it won't work now for technical reasons and cannot work in the future for legal reasons.

**Comment by markuspeloquin** [comment]
It's a shame they improved it, then killed it off. 5.0 and its source is still available at least for when I want to be nostalgic. I gave a Beamer presentation using gsview 5.0 once :P
