### ISSUE TITLE
DAX Studio Package

### ISSUE THREAD

**Issue by dgosbell** [teknowledgist/Chocolatey-packages#33]
If you'd be interested in submitting a pull request to http://github.com/daxstudio/daxstudio I'd be interested in incorporating your DAX Studio package into our repo so that we can update it automatically as part of our build process so that chocolatey always has the latest version.

**Comment by teknowledgist** [comment]
@dgosbell As the principal author of DAX Studio, you have every right to be a maintainer of the package and push the latest version to the Chocolatey repository.  I tried to add you ("dgosbell" assuming you have the same username at Chocolatey.org) as a maintainer.  At that point, you can build/submit packages.  

I'm not sure what kind of a PR you want from me.  Do you want the [entire daxstudio package directory](https://github.com/teknowledgist/Chocolatey-packages/tree/master/automatic/daxstudio)?  But where, and it's only 4 files.

Are you familiar with building Chocolatey?  I use the [AU](https://chocolatey.org/packages/au) package for maintaining the current version only I am calling the updater manually every week or two and not automatically every few hours like the "big names" (i.e. Firefox, Chrome, etc.).  Of course, you don't need AU because you are the application author; you already have the original binary and version.  😄 

Let me know if I can do anything else.

**Comment by UAlbanyErich** [comment]
@dgosbell It looks like you have pushed an updated package, congratulations.  

The Chocolatey automatic testing was disabled on this package due to a dependency reboot requirement, and because there wasn't anything syntactically wrong with the nuspec file, it passed validation.  Finally, as a "trusted" package, the moderators disabled the requirement for manual verification, so it was automatically published.  

Unfortunately however, what you pushed can't work as a Chocolatey package.  It's missing the embedded installer.  You don't have to embed the installer for Chocolatey, but then you would need to change the `chocolateyinstall.ps1` script to download the installer before installing.  In addition, the repository requirement for embedded packages is to update the `VERIFICATION.txt` file with the updated version, URL and checksum.  

Would you like me to update it to a working package?  If you want to take it over entirely, just let me know if you have any questions.  You might want to change the PackageSourceURL attribute in the `.nuspec` file in that case too.

**Comment by teknowledgist** [comment]
@dgosbell It looks like you have pushed an updated package, congratulations.

The Chocolatey automatic testing was disabled on this package due to a dependency reboot requirement, and because there wasn't anything syntactically wrong with the nuspec file, it passed validation. Finally, as a "trusted" package, the moderators disabled the requirement for manual verification, so it was automatically published.

Unfortunately however, what you pushed can't work as a Chocolatey package. It's missing the embedded installer. You don't have to embed the installer for Chocolatey, but then you would need to change the chocolateyinstall.ps1 script to download the installer before installing. In addition, the repository requirement for embedded packages is to update the VERIFICATION.txt file with the updated version, URL and checksum.

Would you like me to update it to a working package? If you want to take it over entirely, just let me know if you have any questions. You might want to change the PackageSourceURL attribute in the .nuspec file in that case too.

**Comment by dgosbell** [comment]
Thanks for logging this. It looks like this is an issue with a first time run where there is no history of previously connected servers. Unfortunately in this case the server name was defaulting to a null and throwing this error. I've fixed this and pushed out a 2.12.2 update.

**Comment by dgosbell** [comment]
Thanks @teknowledgist I think I've fixed the package now in the 2.12.2 update to download the installer on demand. Although I forgot to change the PackageSourceUrl in the nuspec file, but I've fixed this in the DAX Studio repo so that will be updated in the next release. I now have this setup in my AppVeyor build environment so that an updated package is generated with every build and it's pretty much a single click to deploy and new release to github and then one more click to deploy to chocolatey. So it make sense for me to push these to chocolatey so there will be the minimum delay between a new release going live and chocolatey being updated

**Comment by teknowledgist** [comment]
@dgosbell minimum delays was the goal!  

A couple points:

* I would like to request that you include the `<projectSourceUrl>` nuspec tag.  That is especially useful to folks who are interested in OSS.  
* If the code for the Chocolatey package is in a different repository, it would be good to include the `<packageSourceUrl>` tag too.  
* The `<iconUrl>` tag still points to my repository.  I'm OK with that, but if you have a png of the icon somewhere in the DAX Studio repository, it's probably better to use that.  (Be sure to use the CDN link.)
* If you only have a single bit-level installer, you don't need to include the "64" arguments for `Install-ChocolateyPackage`.
* I'm happy to stay on as a co-maintainer, but it's unnecessary.  If you want to be the sole maintainer, feel free to remove me.  (I can't remove myself.)  At some point, I will remove the `daxstudio` folder from my repository since it will be out of date.

Thanks!
