### ISSUE TITLE
(Barrier) ERROR when attempting to upgrade

### ISSUE THREAD

**Issue by lucknaumann** [teknowledgist/Chocolatey-packages#34]
Hi. I hope you are well and thanks again for maintaining this package. I wrote this in the Chocolatey comments section but in case you didn't get notified, I figured I'd open an issue here. I just wanted to let you know I keep getting this ("common" Chocolatey) error when attempting to upgrade:

```posh
ERROR: Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String.
The upgrade of barrier was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\barrier\tools\chocolateyinstall.ps1'.
See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
- barrier (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\barrier\tools\chocolateyinstall.ps1'.
See log for details.
```

This is the log error:

```posh
2020-07-28 11:43:38,043 160164 [ERROR] - ERROR: Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String.
2020-07-28 11:43:38,047 160164 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\barrier\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
```

**Comment by teknowledgist** [comment]
Hi.  Sorry for the far-too-lengthy delay in responding.

Almost certainly, the problem is there have two installer files in the Chocolatey package folder.  Chocolatey is supposed to move everything out before downloading the new version of the package (which contains the latest installer), but I've found that on some machines, it does not.  When the new package looks for the installer, it finds both the old and the new, and the code breaks.  

For the future, I have modified the package to remove the installer once done to eliminate that problem when the next version roles around.

For your current needs (if you haven't already resolved it yourself), go to `%programdata%\chocolatatey\lib\barrier` and delete any .EXE files you see there.  Then try upgrading again.

**Comment by lucknaumann** [comment]
Thanks for the reply! Yeah, there were 2 EXEs in that folder, the old and new. I deleted the entire barrier folder to be sure, then reinstalled the package. I had already manually updated the Barrier program, so hopefully, there won't be any issues with updating the next release. Thanks for fixing.
