### ISSUE TITLE
Install Tabular-Editor hangs

### ISSUE THREAD

**Issue by vestergaardj** [teknowledgist/Chocolatey-packages#38]
Seems like the installation of Tabular Editor 2.14.2 is hanging.

Have tried manually running the choco install tabular-editor -y command from an elevated command prompt locally, but it hangs every time: (have also tried it via Azure DevOps, same issue)

C:\WINDOWS\system32>choco install tabular-editor -y
Chocolatey v0.10.10
Installing the following packages:
tabular-editor
By installing you accept licenses for the packages.
Progress: Downloading tabular-editor 2.12.4... 100%

tabular-editor v2.12.4 [Approved]
tabular-editor package files install completed. Performing other installation steps.
Installing tabular-editor...

**Comment by teknowledgist** [comment]
Hi.  Sorry for the troubles, but I can't reproduce the problem.  I assume you see nothing else on the screen.  What OS are you using?  Can you post the relevant section of the Chocolatey logs?  There should also be a log made by the installer at "%appdata%\local\temp\chocolatey\tabular-editor.2.14.2.msiinstall.log" which might help too.

Have you tried downloading the installer .MSI (or copy it out of the package directory while Chocolatey is hung) and running it manually?  I'm guessing there is some dependency missing or some incompatibility that it is reporting on/asking about, but because it's a silent install, you can't see it.

**Comment by vestergaardj** [comment]
Hi 
The issue is apparently not on your part - so sweats off ;)
After fiddling around I was able to both install manually (local) and via Azure DevOps pipeline (MS hosted agent, Win2019) - I am fairly certain I didn't change anything locally - but can't say for sure on the build agent.
I am happy to close the issue, thank you!
