### ISSUE TITLE
Caesium Image Compressor

### ISSUE THREAD

**Issue by robsonsobral** [teknowledgist/Chocolatey-packages#41]
It looks like the pandemics is helping v2 development.

https://github.com/Lymphatus/caesium-image-compressor/releases

**Comment by teknowledgist** [comment]
@robsonsobral I'm happy to update the package when v2.0 is closer to release (at least in beta).  Since there haven't been enough releases for me to identify a pattern and automate updating the package, I could use your help in watching for the public release.  😄 

I'll leave this open for that purpose until I push a new package version.

**Comment by teknowledgist** [comment]
The Caesium package is being maintained and updated by the author of the software.
