### ISSUE TITLE
[MiKTeX] Shared installation switch

### ISSUE THREAD

**Issue by bazzilic** [teknowledgist/Chocolatey-packages#46]
Would it be possible to add a package parameter to switch whether we want to install for all users (`--shared=yes`) or just for current user (`--shared=no`).

As I understand from looking in the code, in [this line](https://github.com/teknowledgist/Chocolatey-packages/blob/89ce1cb6ed071093e4498af3a55ef930560dd0af/automatic/miktex.install/tools/chocolateyinstall.ps1#L134) `--shared` is passed, which is equivalent to `--shared=yes`, so it's always installed for all users.

**Comment by teknowledgist** [comment]
I'm highly resistant to do that.  Chocolatey packages are supposed to be machine installs, not user installs.  That's because Chocolatey manages packages at the machine level and not per user.

The few packages I have tried to use that are stuck with user installs (because the installer is built that way) drive me nuts because all users can see that Chocolatey thinks it is installed, but (usually) only the user who installed it can use it and only that user can successfully uninstall it.  The [atom](http://disq.us/p/19xblgt) and [github](http://disq.us/p/1vrnafi) packages are like this.  I have given up using Chocolatey with them because I run as a non-admin, and my unprivileged user can't install/uninstall them, nor can it use them.  

I've declined building packages for other applications (like [StandardNotes](https://github.com/chocolatey-community/chocolatey-package-requests/issues/732)) because they could not be made into machine installs even though I would love to see them on the Chocolatey repository.

All that said, I am the maintainer of the miktex.portable package, and that could be built in a way to give you pretty much what you want.  I haven't done much with it because I'm not sure how to "do it right", but I will poke at it to see what I can come up with.

**Comment by bazzilic** [comment]
Half of the most popular Chocolatey packages are user installs though: VS Code, Spotify, Atom, etc.

The problem with MiKTeX in particular is that machine-wide install is so much harder to manage. It has the main package repo that can only be accessed as Administrator and per-user package repos, and that becomes a source of all kinds of problems. The biggest one is that on-the-fly installation of packages requires UAC elevation but if you are not using the built-in editor for TeX files and instead use say VS Code, it doesn't pop up the UAC window and just gets stuck.

In the case of MiKTeX it makes sense to at least have a switch to have a per-user install.

**Comment by teknowledgist** [comment]
How many of those popular, user-install package applications have an installer with the ability/option of a machine install?  Probably few if any.

I'll consider your request.  

I just added the license -- GPLv3 -- so feel free to play around.

**Comment by bazzilic** [comment]
> How many of those popular, user-install package applications have an installer with the ability/option of a machine install?

My point is rather that machine-wide installation purity is not really in the cards for Chocolatey. Different software comes with different quirks. If Chocolatey was not an after-thought so to speak and was around since the early days of Windows, then it would have the luxury to dictate how software should be installed. And I'd prefer it that way, but alas.

> I'll consider your request.

Thanks!

> I just added the license -- GPLv3 -- so feel free to play around.

Cool. I maintain a few packages so I can fork your MiKTeX package and add the per-user installation option but I'd rather not multiply entities without necessity :)

**Comment by teknowledgist** [comment]
@bazzilic Sorry for the delay - life gets in the way sometimes.

There appears to be [a bug in the installer](https://github.com/MiKTeX/miktex/issues/847) where what you use for `--shared=` doesn't matter if you are running as an elevated admin.  Because Chocolatey elevates by default, I'm not sure how to create a `--shared=no` package option.  

Did you fork my package and get it working using the `miktexsetup-standalone.exe` application?  

TBPH, I am a sysadmin who needs to deploy MiKTeX, but I am not a MiKTeX user.  Maybe there is a combination of `--user-config=dir`, `--user-data=dir`, and `--user-install=dir` directives on an unshared install that will do what you want?  (assuming those settings actually work as promised)  If you know how to adjust MiKTeX to make it better for shared users while protecting those users from each other, please let me know and I'll try to incorporate that into the package.

Thanks.

**Comment by bazzilic** [comment]
Hi, I didn't manage to play around with it. I pinged them in the Miktex issue tracker wrt `--shared=no` not working, let's see if they fix this. Then making per-user installations through Choco will be trivial.

Main reason why private installation is preferred for single users is the on-the-fly package installation feature of miktex. In a private installation it just works, but in a machine-wide installation it only works if you use the miktex own tex editor (texworks is it?). If you use another editor, on-the-fly package installation just hangs the compilation (I assume because it can't show the UAC window and waits endlessly for user confirmation).

**Comment by bazzilic** [comment]
It appears to be fixed now in the Miktex installer (https://github.com/MiKTeX/miktex/issues/847). Would it be possible to add the non-shared install option to the package now?

**Comment by teknowledgist** [comment]
@bazzilic I finally figured out how to get around the issue, and the MiKTeX package (v21.8) I just pushed now has a `/thisuser` package parameter that utilizes the `--shared=no` command option on the install.  Thus, you should be able to do:

    choco install miktex -y --params '"/thisuser"'

and you will get what you asked for.  😄  Obviously, if there are other users of the computer, They will both not see MiKTeX or be able to use it **and** will not be able to install it via Chocolatey (for themselves or the machine).  

One thing I noticed is that the MiKTeX uninstall for non-shared installs like this does not remove the Start Menu shortcuts.  It's not enough of a worry for me to deal with, so I'm leaving it.

I hope that works as you need.  Let me know if I messed it up somehow.

**Comment by bazzilic** [comment]
This seems to work perfectly! I think this issue can be closed. Thanks a lot!
