### ISSUE TITLE
`rsat` Installation is skipped for Windows 10 Enterprise multi-session image

### ISSUE THREAD

**Issue by schnerring** [teknowledgist/Chocolatey-packages#56]
The installation skips with the following warning 

https://github.com/teknowledgist/Chocolatey-packages/blob/66e8db994372cfad4f83728accc8256fe2f400a8/manual/rsat/tools/chocolateyinstall.ps1#L13-L16

Here is my `$osInfo` output:

```
Version            : 10.0.19043
ProductType        : 3
Caption            : Microsoft Windows 10 Enterprise for Virtual Desktops
OperatingSystemSKU : 175
BuildNumber        : 19043
```

**Comment by teknowledgist** [comment]
https://docs.microsoft.com/en-us/azure/virtual-desktop/windows-10-multisession-faq#why-does-my-application-report-windows-10-enterprise-multi-session-as-a-server-operating-system

I'm not sure what `detect the ProductType is set to Client` means.  I'm not sure how to make an exception if the product type is the same as "server".  I can't rely on the caption because that is language dependent, and even for English, there is no definitive list of potential captions to bank on.

If you know of another way to broadly and definitively identify multi-session Win10, I can try to include that in the RSAT package, but I don't have access to it for testing.

**Comment by schnerring** [comment]
It seems to be common practice to check whether `OperatingSystemSKU` equals `175`

The article [Configure Microsoft Endpoint Configuration Manager (official Windows Virtual Desktop documentation)](https://docs.microsoft.com/en-us/azure/virtual-desktop/configure-automatic-updates#create-a-query-based-collection) suggests the same:

```
select
SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client
from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on
SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId where
SMS_G_System_OPERATING_SYSTEM.OperatingSystemSKU = 175
```

[It was also tweeted about](https://twitter.com/brinkhoff_c/status/1244557292214915072?)

I am no expert on the subject, but I use the WMI query to identify WVD session hosts in Active Directory so far it works flawlessly.
