### ISSUE TITLE
Fusion - LDV - Win10 Lenovo X1C Gen 7  menu window comrepessed how can I adjust?

### ISSUE THREAD

**Issue by edh635** [teknowledgist/Chocolatey-packages#59]
Need to resize inside the LDV window  - can't seem to grab the left edge of image display sub-window.
![image](https://user-images.githubusercontent.com/41864272/126514193-95635459-f113-411d-aff6-57d9afa7a29b.png)

**Comment by teknowledgist** [comment]
I'm sorry, but I only maintain the Chocolatey package for Fusion LDV that makes it easy to install/uninstall/upgrade the software.  

Your issue is with the software itself and should probably be addressed by the developer of the application (at the bottom of [this page](http://forsys.sefs.uw.edu/fusion/fusion_overview.html)).
