### ISSUE TITLE
[Chocolatey-Font-Helpers.extension] warning (but actually error) sometimes upgrading a font

### ISSUE THREAD

**Issue by flcdrg** [teknowledgist/Chocolatey-packages#67]
Seen this happen myself today and also by others in comments at https://community.chocolatey.org/packages/FiraCode#discussion

```text
WARNING: An error occured installing 'C:\Users\<username>\AppData\Local\Temp\chocolatey\FiraCode\variable_ttf\FiraCode-VF.ttf'
WARNING: Exception: The requested operation cannot be performed on a file with a user-mapped section open.

WARNING: The requested operation cannot be performed on a file with a user-mapped section open.

6 fonts were installed.
WARNING: 1 submitted font paths failed to install.
```

Not sure if there's a way to work around it, but mentioning it here.

**Comment by teknowledgist** [comment]
This is happening on upgrade, not install, right?  I can't see how a new file could be locked.

I don't think there is much this extension could do.  At best (with a lot of work), it could identify if a font file is already installed and is locked/in-use and decline to attempt the install/upgrade.  However, that wouldn't get you any closer to the solution.  It's way beyond scope for this extension to try to identify what is locking the current font file let alone try to unlock it for replacement.  

I would argue that the font package maintainer could improve the documentation and/or code to warn people against trying to upgrade the font when VS Code is in (recent) use.  That wouldn't make sense for this extension because there are a lot of fonts that could depend on this that would *never* be used in VS Code.

Just as an aside, in testing this extension and/or building my own font packages, I've been stuck with font files on the desktop and other places (i.e. NOT installed) that were hopelessly locked, immovable and unreleased until a reboot simply because I previewed them.  That is a terrible design on MS's part.

**Comment by flcdrg** [comment]
FYI in my case I'm pretty sure I didn't have VS Code open when I did the upgrade, which is why my best guess was antivirus might have had the file locked briefly.

I guess one approach could be to check for this error and do some kind of retry (given that in my case it did work when I tried the upgrade again).

**Comment by teknowledgist** [comment]
In my limited experience, font files can remain locked long after the application that used them has been closed.  I believe I've even seen them remain locked through a reboot.

**Comment by jessestricker** [comment]
I had the same issue with my font package ([adobe-source-serif](https://community.chocolatey.org/packages/adobe-source-serif)).

As a workaround, if you can't upgrade the packages using this helper via `choco upgrade ...`, it **does work** if you just uninstall and then install them again.
Very weird that uninstalling works though, when the upgrade reports a "file locked" error.

I wonder if this workaround can be implemented in the helper as fallback behaviour?

**Comment by teknowledgist** [comment]
@jessestricker I am willing to give it a shot with a nested, *try to upgrade -> if fails for open user-map -> try to remove -> if succeeds, try to install again* setup.

However, I need a way to recreate the error.  Do you have a process that will set up this failure in a relatively reliable way?

**Comment by jessestricker** [comment]
I am on Windows 11, this might be relevant.

try this for a replication:
1. install an old version of a font package:
   `choco install -y adobe-source-serif --version=4.004`
2. use the font in some software or just look at it in the Windows Settings app
3. reboot PC
4. try to upgrade, **this should fail**:
   `choco upgrade -y adobe-source-serif`
