### ISSUE TITLE
Stopping the "DraftSight API Service" on upgrades

### ISSUE THREAD

**Issue by basictheprogram** [teknowledgist/Chocolatey-packages#7]
I've run into a problem upgrading  DraftSight when the "DraftSight API Service" is running.

Stopping the service allows the choco upgrade to work properly.

I see chocolateybeforemodify.ps1 can be put into the tools directory and the service could be stopped before the upgrade?

**Comment by teknowledgist** [comment]
Sorry about that.  I have included the appropriate chocolateyBeforeModify.ps1 in the latest package version (v2018.00/2018sp0) that I just submitted for moderation.

Since that would not have fixed your current issue, and would not cause anyone who installs the Chocolatey package overtop of a non-Chocolatey-installed DraftSight version, I also included the code in the chocolateyInstall.ps1 script.  It is a minor inefficiency to have it in both places, but improves the experience for more users (including yourself).
