### ISSUE TITLE
Checksum doesn't match

### ISSUE THREAD

**Issue by andy-vdg** [teknowledgist/Chocolatey-packages#70]
automatic/tableau-public/tools/chocolateyinstall.ps1 seems to have an outdated Checksum. 
I get:
`ERROR: Checksum for 'C:\[...]\TableauPublicDesktop-64bit-2022-1-0.exe' did not meet 'b43f93f9a3051ca22284b86359bbf8c6b385bdd5053d8fb8bc68a27939eae389' for checksum type 'sha256'.`

**Comment by teknowledgist** [comment]
Well, that would be because I needed to update the package to the latest version!  I've just done so and submitted it to the public repository for moderation.  It can take a few days for packages to clear.  If you need to install it in the mean time, use the `--version 2022.1` switch.

Sorry for falling behind, and thanks for the heads up.
