### ISSUE TITLE
RSAT internalize not possible

### ISSUE THREAD

**Issue by kokspflanze** [teknowledgist/Chocolatey-packages#75]
**Describe the bug**
The Download of the rsat package with `internalize` runs into an error.
I think the problem comes from https://github.com/teknowledgist/Chocolatey-packages/blob/master/manual/rsat/tools/chocolateyinstall.ps1#L62 and choco try to replace the link and fails.

**To Reproduce**
1. Run `choco.exe download rsat -r --no-progress --internalize --force --source=https://chocolatey.org/api/v2/`
3. See error

**Expected behavior**
Download RSAT and run the internalize 

**Error**
````
RSAT v2.1809.0.20210815 (forced) [Approved]
Found internalizable Chocolatey functions. Inspecting values for remote resources.
Found 'https://www.microsoft.com/download/confirmation.aspx?id=28972' for replacement.
Found 'https://www.microsoft.com/download/confirmation.aspx?id=39296' for replacement.
Found 'https://www.microsoft.com/download/confirmation.aspx?id=45520' for replacement.
Found 'https[^' for replacement.
Encountered error downloading package rsat v:
System.UriFormatException: Ungültiger URI: Das URI-Format konnte nicht bestimmt werden.
   bei System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bei chocolatey.licensed.infrastructure.app.commandresources.RemoteDownloader.get_remote_file_name(String url, String userAgent, String defaultName, PSHost host)
   bei chocolatey.licensed.infrastructure.app.commands.ProChocolateyDownloadCommand.process_downloaded_package(IPackage package, String downloadLocation, ChocolateyConfiguration configuration)
   bei chocolatey.infrastructure.app.nuget.NugetCommon.<>c__DisplayClass14.<GetPackageManager>b__11(Object s, PackageOperationEventArgs e)
   bei NuGet.PackageManager.OnInstalled(PackageOperationEventArgs e)
   bei NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver)
   bei NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   bei chocolatey.licensed.infrastructure.app.commands.ProChocolateyDownloadCommand.download_packages(String packageName, String packageVersion, String downloadLocation, ChocolateyConfiguration configuration)
````

**Comment by teknowledgist** [comment]
Hi.  

I do not have a licensed version of Chocolatey, so I have no experience with those paid features and can only guess as to exactly what they do or how they work.  That said, I have two comments:

1. I'm not sure it makes sense to try to internalize RSAT at this point.  For Win10 prior to 1809, there was an actual install file that `--internalize` could fold into a package.  Since that release, all the RSAT tools are added as features that install directly over the network from either Microsoft or an internal update server.  This package doesn't actually download any file.  Many of the RSAT downloads for those older versions are no longer downloadable, and even if they are, it would be bad practice to be using those older versions of Windows to manage AD systems.
2. As much as I hate to shift blame, I feel like this is more of a problem with Chocolatey's `--internalize` feature than it is a problem with my code.  That features has a very difficult job to parse code written by *anyone* and -- effectively -- guess as to what to modify.  In this case, it guessed wrong, and I understand why.  I'm not quite sure how to "fix" my code since it appears the `--internalize` features is just looking for strings that start with 'https', and I also need to define a string with that same start.  Even if I do adjust my code so that `--internalize` works (which I can't directly test), there could easily be another package that will break that feature for the same or similar reasons which leads me to conclude it is better for Chocolatey to fix their end.

If you **really** need to internalize RSAT, I would suggest you ask for support from Chocolatey (since you have a paid version).  Let them earn their worth by figuring out how to fix the problem.  If they refuse or push the blame back onto me, let me know and I'll see what I can do.

I'll leave this open for now.
