### ISSUE TITLE
OneDrive Error with reg unload

### ISSUE THREAD

**Issue by asheroto** [teknowledgist/Chocolatey-packages#92]
**Describe the bug**
If you already have installed OneDrive, then uninstall it through Add/Remove programs, then try to force install OneDrive with this choco package, it will produce the following error:

```powershell
ERROR: The parameter is incorrect.
Microsoft.PowerShell.Commands.WriteErrorException
ERROR: Running ["C:\Windows\system32\reg.exe" UNLOAD HKU\DefaultUserTemplate] was not successful. Exit code was '1'. See log for possible error messages.
  onedrive may be able to be automatically uninstalled.
The install of onedrive was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\onedrive\tools\chocolateyinstall.ps1'.
 See log for details.
```

**To Reproduce**
1. Install OneDrive `choco install onedrive`
2. Uninstall OneDrive in Add/Remove programs
3. Install OneDrive with force `choco install onedrive --force`
4. You should see the error

**Expected behavior**
Should reinstall. This issue was described here as well:
http://disq.us/p/2eody8i

`chocolatey.log` is here, see line 473:
https://gist.github.com/asheroto/c3a5a7a98ea2e210d679689b39b8e651#file-onedrive_choco_debug_chocolatey-log-L473

**Screenshots**
![image](https://github.com/teknowledgist/Chocolatey-packages/assets/49938263/d05772a0-60cb-470c-a4dd-12274c3f09fc)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

**Additional info:**
Actually tested this and confirmed the issue in Windows Sandbox. So not just one computer. 😊

**Comment by teknowledgist** [comment]
Hi.  I was not able to reproduce the problem in Win10, and I don't have a Windows 11 machines at the moment.  

Nevertheless, because OneDrive was being installed and the failure point was just an attempt to "clean up", it didn't make sense to cause the entire package to fail.  I tried to fix the package install script to output only a warning if the particular failure you saw occurs rather than the Chocolatey claiming OneDrive failed to install.  

The updated package has been submitted.

**Comment by asheroto** [comment]
Okay cool, that should work, thanks. Closing the issue.
